### ISSUE TITLE
[status] keyboard interaction

### ISSUE THREAD

**Issue by GabrieleRisso** [jon4hz/fztea#23]
Hello, great repo. Very useful tool. 
I wanted to know if there is interest for handling  keyboard inputs for PC  and forwarding them to the virtual keyboard of the filpper. I  saw that using flipper-cli at the moment it's not possible to so. Is fztea relying on it ?

Thanks

**Comment by jon4hz** [comment]
Do you mean like free text input, for tasks like naming files, etc? If so, I'm afraid that isn't possible, or at least I don't know how to do that. 
Flippers gRPC only supports very limited key input. 
(see: https://github.com/flipperdevices/flipperzero-protobuf/blob/6460660237005d02d5c223835659b40e373bade9/gui.proto#L6)

**Comment by jon4hz** [comment]
Going to close this, feel free to reopen if you want to add something :)
