### ISSUE TITLE
Use with iterm2 on Mac

### ISSUE THREAD

**Issue by ifuchs** [jon4hz/fztea#31]
By default, it seems that iterm2 gets the data for the images but does not display them as images of the Flipper. Is it possible to use iterms2 for this purpose?

**Comment by jon4hz** [comment]
> but does not display them as images of the Flipper

Not sure if I'm missunderstanding you but `fztea` doesn't project any data to the flipper. What it does is mirroring the flippers screen __to__ the terminal. 
Does that answer your question?

**Comment by ifuchs** [comment]
Sorry if I wasn’t clear. I mean that iterm2 is not showing the F0 screen.
it is showing the stream of characters that constitute the screen.  Iterm2
doesn’t no how to display  it. Perhaps there is a setting for that.

**Comment by jon4hz** [comment]
Could you send a screenshot? Unfortunately I dont have a mac so I cant reproduce it that easily.
